/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Conexionbd.Consultas;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;



public class Consulta extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Consulta.class.getName());

    /**
     * Creates new form Consultas1
     */
    public Consulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        txtAlumno = new javax.swing.JTextField();
        txtCurso = new javax.swing.JTextField();
        btnconsultacurso = new javax.swing.JButton();
        btnconsultaalumno = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        txtRetiro = new javax.swing.JTextField();
        btnconsultamatricula = new javax.swing.JButton();
        btnconsultaretiro = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(0, 0, 102));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("ALUMNOS Y CURSOS");

        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Codigo de Alumno:");

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Codigo de Curso:");

        btnconsultacurso.setBackground(new java.awt.Color(255, 255, 255));
        btnconsultacurso.setForeground(new java.awt.Color(0, 0, 0));
        btnconsultacurso.setText("Consultar Curso");
        btnconsultacurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultacursoActionPerformed(evt);
            }
        });

        btnconsultaalumno.setBackground(new java.awt.Color(255, 255, 255));
        btnconsultaalumno.setForeground(new java.awt.Color(0, 0, 0));
        btnconsultaalumno.setText("Consultar Alumno");
        btnconsultaalumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultaalumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(jLabel51)
                .addGap(18, 18, 18)
                .addComponent(txtAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(jLabel52)
                .addGap(18, 18, 18)
                .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(jLabel50)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(btnconsultaalumno, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnconsultacurso)
                .addGap(153, 153, 153))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel50)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel51, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel52)
                                .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addComponent(btnconsultaalumno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(71, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnconsultacurso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Alumno y Curso", jPanel8);

        jPanel7.setBackground(new java.awt.Color(0, 0, 102));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("MATRICULAS Y RETIROS");

        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Numero de Matricula: ");

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Numero de Retiro:");

        btnconsultamatricula.setBackground(new java.awt.Color(255, 255, 255));
        btnconsultamatricula.setForeground(new java.awt.Color(0, 0, 0));
        btnconsultamatricula.setText("Consultar Matricula");
        btnconsultamatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultamatriculaActionPerformed(evt);
            }
        });

        btnconsultaretiro.setBackground(new java.awt.Color(255, 255, 255));
        btnconsultaretiro.setForeground(new java.awt.Color(0, 0, 0));
        btnconsultaretiro.setText("Consultar Retiro");
        btnconsultaretiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultaretiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel47))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel49)
                        .addGap(26, 26, 26)
                        .addComponent(txtRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(btnconsultamatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnconsultaretiro)
                .addGap(125, 125, 125))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel47)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel48)
                            .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel49)
                            .addComponent(txtRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnconsultamatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnconsultaretiro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Matricula y Retiro", jPanel7);

        jPanel10.setBackground(new java.awt.Color(0, 0, 102));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("CONSULTA DE DATOS");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel43)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel43)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsultamatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultamatriculaActionPerformed
        // TODO add your handling code here:
        String idTexto = txtMatricula.getText().trim(); // Campo de número de matrícula
        if (idTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el número de matrícula.");
            return;
        }

        try {
            int id = Integer.parseInt(idTexto);
            Consultas consultas = new Consultas();
            ResultSet rs = consultas.listarMatriculas(); // Aquí podrías hacer un método buscarMatriculaPorId
            boolean encontrado = false;
            while (rs.next()) {
                if (rs.getInt("idMatricula") == id) {
                    String datos = "Alumno: " + rs.getString("alumno_nombre") + " " + rs.getString("alumno_apellidos")
                            + "\nCurso: " + rs.getString("curso_asignatura")
                            + "\nFecha: " + rs.getDate("fecha")
                            + "\nHora: " + rs.getTime("hora");
                    JOptionPane.showMessageDialog(this, datos);
                    encontrado = true;
                    break;
                }
            }
            if (!encontrado) {
                JOptionPane.showMessageDialog(this, "Matrícula no encontrada.");
            }
        } catch (NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al consultar matrícula.");
        }
    }//GEN-LAST:event_btnconsultamatriculaActionPerformed

    private void btnconsultaalumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultaalumnoActionPerformed
        // TODO add your handling code here:

        String idTexto = txtAlumno.getText().trim(); // Campo de código de alumno
        if (idTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el código de alumno.");
            return;
        }

        try {
            int id = Integer.parseInt(idTexto);
            Consultas consultas = new Consultas();
            ResultSet rs = consultas.buscarAlumnoPorId(id);
            if (rs != null && rs.next()) {
                String datos = "Nombre: " + rs.getString("nombre")
                        + "\nApellidos: " + rs.getString("apellidos")
                        + "\nDNI: " + rs.getString("dni")
                        + "\nEdad: " + rs.getInt("edad")
                        + "\nCelular: " + rs.getInt("celular")
                        + "\nEstado: " + estadoTexto(rs.getInt("estado"));
                JOptionPane.showMessageDialog(this, datos);
            } else {
                JOptionPane.showMessageDialog(this, "Alumno no encontrado.");
            }
        } catch (NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al consultar alumno.");
        }
    }//GEN-LAST:event_btnconsultaalumnoActionPerformed

    private void btnconsultacursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultacursoActionPerformed
        // TODO add your handling code here:
        String idTexto = txtCurso.getText().trim(); // Campo de código de curso
        if (idTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el código de curso.");
            return;
        }

        try {
            int id = Integer.parseInt(idTexto);
            Consultas consultas = new Consultas();
            ResultSet rs = consultas.buscarCursoPorId(id);
            if (rs != null && rs.next()) {
                String datos = "Asignatura: " + rs.getString("asignatura")
                        + "\nCiclo: " + rs.getInt("ciclo")
                        + "\nCréditos: " + rs.getInt("creditos")
                        + "\nHoras: " + rs.getInt("horas");
                JOptionPane.showMessageDialog(this, datos);
            } else {
                JOptionPane.showMessageDialog(this, "Curso no encontrado.");
            }
        } catch (NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al consultar curso.");
        }
    }//GEN-LAST:event_btnconsultacursoActionPerformed

    private void btnconsultaretiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultaretiroActionPerformed
        // TODO add your handling code here:
        String idTexto = txtRetiro.getText().trim(); // Campo de número de retiro
        if (idTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el número de retiro.");
            return;
        }
        
        
        try {
            int id = Integer.parseInt(idTexto);
            Consultas consultas = new Consultas();
            ResultSet rs = consultas.listarRetiros(); // Igual, podrías hacer buscarRetiroPorId
            boolean encontrado = false;
            while (rs.next()) {
                if (rs.getInt("idRetiro") == id) {
                    String datos = "Alumno: " + rs.getString("alumno_nombre") + " " + rs.getString("alumno_apellidos")
                            + "\nCurso: " + rs.getString("curso_asignatura")
                            + "\nFecha: " + rs.getDate("fecha")
                            + "\nHora: " + rs.getTime("hora");
                    JOptionPane.showMessageDialog(this, datos);
                    encontrado = true;
                    break;
                }
            }
            if (!encontrado) {
                JOptionPane.showMessageDialog(this, "Retiro no encontrado.");
            }
        } catch (NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al consultar retiro.");
        }
    }//GEN-LAST:event_btnconsultaretiroActionPerformed

    private String estadoTexto(int estado) {
    return switch (estado) {
        case 0 -> "Registrado";
        case 1 -> "Matriculado";
        case 2 -> "Retirado";
        default -> "Desconocido";
    };
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Consulta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultaalumno;
    private javax.swing.JButton btnconsultacurso;
    private javax.swing.JButton btnconsultamatricula;
    private javax.swing.JButton btnconsultaretiro;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtAlumno;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtRetiro;
    // End of variables declaration//GEN-END:variables
}
