/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Logica.Consultas;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Conexionbd.Conexionbd;

public class Consulta extends javax.swing.JFrame {

    /**
     * Creates new form Consultas1
     */
    public Consulta() {
        initComponents();
        cargartablaAlumno("");
        cargartablaCurso("");
        cargartablaMatricula("");
        cargartablaRetiro("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        txtAlumno = new javax.swing.JTextField();
        txtCurso = new javax.swing.JTextField();
        btncargardenuevocurso = new javax.swing.JButton();
        btncargardenuevoalumno = new javax.swing.JButton();
        btnconsultarAlumno = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlumno = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCurso = new javax.swing.JTable();
        btnconsultarCurso = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        txtRetiro = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaMatricula = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaRetiro = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 102));
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(0, 0, 102));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("ALUMNOS Y CURSOS");

        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Código de Alumno:");

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Código de Curso:");

        btncargardenuevocurso.setBackground(new java.awt.Color(255, 255, 255));
        btncargardenuevocurso.setForeground(new java.awt.Color(0, 0, 0));
        btncargardenuevocurso.setText("Cargar tabla");
        btncargardenuevocurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargardenuevocursoActionPerformed(evt);
            }
        });

        btncargardenuevoalumno.setBackground(new java.awt.Color(255, 255, 255));
        btncargardenuevoalumno.setForeground(new java.awt.Color(0, 0, 0));
        btncargardenuevoalumno.setText("Cargar tabla");
        btncargardenuevoalumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargardenuevoalumnoActionPerformed(evt);
            }
        });

        btnconsultarAlumno.setBackground(new java.awt.Color(255, 255, 255));
        btnconsultarAlumno.setForeground(new java.awt.Color(0, 0, 0));
        btnconsultarAlumno.setText("Consultar Alumno");
        btnconsultarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarAlumnoActionPerformed(evt);
            }
        });

        tablaAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombres", "Apellidos", "DNI", "Edad", "Celular", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaAlumno);

        tablaCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Asignatura", "Ciclo", "Nº Créditos", "Horas"
            }
        ));
        jScrollPane2.setViewportView(tablaCurso);

        btnconsultarCurso.setBackground(new java.awt.Color(255, 255, 255));
        btnconsultarCurso.setForeground(new java.awt.Color(0, 0, 0));
        btnconsultarCurso.setText("Consultar Curso");
        btnconsultarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(jLabel50)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btncargardenuevoalumno, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(jLabel51)
                                        .addGap(55, 55, 55)
                                        .addComponent(txtAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(btnconsultarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnconsultarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(btncargardenuevocurso, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jLabel52)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)))
                .addGap(28, 28, 28))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51))
                .addGap(36, 36, 36)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncargardenuevoalumno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnconsultarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncargardenuevocurso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnconsultarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alumno y Curso", jPanel8);

        jPanel7.setBackground(new java.awt.Color(0, 0, 102));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("MATRICULAS Y RETIROS");

        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Código de Matrícula: ");

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Código de Retiro:");

        txtMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMatriculaKeyReleased(evt);
            }
        });

        txtRetiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRetiroKeyReleased(evt);
            }
        });

        tablaMatricula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Alumno", "Curso", "Fecha", "Hora"
            }
        ));
        jScrollPane3.setViewportView(tablaMatricula);

        tablaRetiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cod.Matricula", "Fecha", "Hora"
            }
        ));
        jScrollPane4.setViewportView(tablaRetiro);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel48)
                                .addGap(97, 97, 97)
                                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel49)
                                .addGap(72, 72, 72)
                                .addComponent(txtRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jLabel47)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel47)
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel48)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel49)
                        .addComponent(txtRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Matricula y Retiro", jPanel7);

        jPanel10.setBackground(new java.awt.Color(0, 0, 102));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("CONSULTA DE DATOS");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel43)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel43)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncargardenuevoalumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargardenuevoalumnoActionPerformed
        // TODO add your handling code here:
        cargartablaAlumno("");
    }//GEN-LAST:event_btncargardenuevoalumnoActionPerformed

    private void btncargardenuevocursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargardenuevocursoActionPerformed
        // TODO add your handling code here:
        cargartablaCurso("");
    }//GEN-LAST:event_btncargardenuevocursoActionPerformed

    private void btnconsultarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarAlumnoActionPerformed
        // TODO add your handling code here:
        String codigo = txtAlumno.getText().trim(); // tin() para evitar espacios
        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "A El campo de búsqueda está vacio. Ingrese un codigo.");
        } else {
            cargartablaAlumno(codigo);
            // aqui internamente ya mostrará encontrado" o "no encontrado"
        }
    }//GEN-LAST:event_btnconsultarAlumnoActionPerformed

    private void btnconsultarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarCursoActionPerformed
        // TODO add your handling code here:
        String codigo = txtCurso.getText().trim(); // tin() para evitar espacios
        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "A El campo de búsqueda está vacio. Ingrese un codigo.");
        } else {
            cargartablaCurso(codigo);
            // aqui internamente ya mostrará encontrado" o "no encontrado"
        }
    }//GEN-LAST:event_btnconsultarCursoActionPerformed

    private void txtMatriculaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatriculaKeyReleased
        // TODO add your handling code here:
        String codigo = txtMatricula.getText();
        cargartablaMatricula(codigo);
    }//GEN-LAST:event_txtMatriculaKeyReleased

    private void txtRetiroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRetiroKeyReleased
        // TODO add your handling code here:
        String codigo = txtRetiro.getText();
        cargartablaRetiro(codigo);
    }//GEN-LAST:event_txtRetiroKeyReleased

    private void cargartablaAlumno(String filtro) {
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaAlumno.getModel();
        modeloTabla.setRowCount(0);

        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        boolean encontrado = false; // bandera

        int[] anchos = {120, 100, 100, 110, 70, 80, 70};
        for (int i = 0; i < tablaAlumno.getColumnCount(); i++) {
            tablaAlumno.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        try {
            Conexionbd co = new Conexionbd();
            Connection con = co.getConnection();

            // Consulta con filtro (si está vacio, trae todos)
            String sql;
            if (filtro.equals("")) {
                sql = "SELECT codAlumno, nombre, apellidos, dni, edad, celular, estado FROM Alumno";
                ps = con.prepareStatement(sql);
            } else {
                sql = "SELECT codAlumno, nombre, apellidos, dni, edad, celular, estado FROM Alumno WHERE codAlumno LIKE ?";
                ps = con.prepareStatement(sql);
                ps.setString(1, "%" + filtro + "%"); // filtro seguro con PreparedStatement
            }
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while (rs.next()) {
                Object[] fila = new Object[columnas];
                for (int indice = 0; indice < columnas; indice++) {
                    fila[indice] = rs.getObject(indice + 1);
                }
                modeloTabla.addRow(fila);
                encontrado = true;
            }
            if (!filtro.equals("")) {
                if (encontrado) {
                    JOptionPane.showMessageDialog(null, "Alumno encontrado.");
                } else {
                    JOptionPane.showMessageDialog(null, "A No se encontraron Alumnos con ese codigo.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    private void cargartablaCurso(String filtro) {
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaCurso.getModel();
        modeloTabla.setRowCount(0);

        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        boolean encontrado = false; // bandera

        int[] anchos = {100, 150, 60, 80, 70};
        for (int i = 0; i < tablaCurso.getColumnCount(); i++) {
            tablaCurso.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        try {
            Conexionbd co = new Conexionbd();
            Connection con = co.getConnection();

            // Consulta con filtro (si está vacio, trae todos)
            String sql;
            if (filtro.equals("")) {
                sql = "SELECT codCurso, asignatura, ciclo, creditos, horas FROM Curso";
                ps = con.prepareStatement(sql);
            } else {
                sql = "SELECT codCurso, asignatura, ciclo, creditos, horas  FROM Curso WHERE codCurso LIKE ?";
                ps = con.prepareStatement(sql);
                ps.setString(1, "%" + filtro + "%"); // filtro seguro con PreparedStatement
            }
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while (rs.next()) {
                Object[] fila = new Object[columnas];
                for (int indice = 0; indice < columnas; indice++) {
                    fila[indice] = rs.getObject(indice + 1);
                }
                modeloTabla.addRow(fila);
                encontrado = true;
            }
            if (!filtro.equals("")) {
                if (encontrado) {
                    JOptionPane.showMessageDialog(null, "Curso encontrado.");
                } else {
                    JOptionPane.showMessageDialog(null, "A No se encontraron Cursos con ese codigo.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    private void cargartablaMatricula(String filtro) {
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaMatricula.getModel();
        modeloTabla.setRowCount(0);

        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;

        int[] anchos = {100, 100, 100, 100, 100};
        for (int i = 0; i < tablaMatricula.getColumnCount(); i++) {
            tablaMatricula.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        try {
            Conexionbd co = new Conexionbd();
            Connection con = co.getConnection();

            String sql;
            String baseSql = "SELECT m.codMatricula, a.apellidos, c.asignatura, m.fecha, m.hora "
                       + "FROM Matricula m JOIN Alumno a ON m.idAlumno = a.idAlumno "
                       + "JOIN Curso c ON m.idCurso = c.idCurso ";
            
            if (filtro.equals("")) {
                sql = baseSql;
                ps = con.prepareStatement(sql);
            } else {
                sql = baseSql + " WHERE codMatricula LIKE ?";
                ps = con.prepareStatement(sql);
                ps.setString(1, "%" + filtro + "%");
            }

            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while (rs.next()) {
                Object[] fila = new Object[columnas];
                for (int indice = 0; indice < columnas; indice++) {
                    fila[indice] = rs.getObject(indice + 1);
                }
                modeloTabla.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    private void cargartablaRetiro(String filtro) {
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaRetiro.getModel();
        modeloTabla.setRowCount(0);

        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;

        int[] anchos = {100, 100, 100, 100};
        for (int i = 0; i < tablaRetiro.getColumnCount(); i++) {
            tablaRetiro.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        try {
            Conexionbd co = new Conexionbd();
            Connection con = co.getConnection();

            String sql;
            String baseSql = "SELECT r.codRetiro, m.codMatricula, r.fecha, r.hora "
                       + "FROM Retiro r JOIN Matricula m ON r.idMatricula = m.idMatricula ";
            
            if (filtro.equals("")) {
                sql = baseSql;
                ps = con.prepareStatement(sql);
            } else {
                sql = baseSql + " WHERE r.codRetiro LIKE ?";
                ps = con.prepareStatement(sql);
                ps.setString(1, "%" + filtro + "%");
            }

            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while (rs.next()) {
                Object[] fila = new Object[columnas];
                for (int indice = 0; indice < columnas; indice++) {
                    fila[indice] = rs.getObject(indice + 1);
                }
                modeloTabla.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {

        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Consulta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncargardenuevoalumno;
    private javax.swing.JButton btncargardenuevocurso;
    private javax.swing.JButton btnconsultarAlumno;
    private javax.swing.JButton btnconsultarCurso;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaAlumno;
    private javax.swing.JTable tablaCurso;
    private javax.swing.JTable tablaMatricula;
    private javax.swing.JTable tablaRetiro;
    private javax.swing.JTextField txtAlumno;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtRetiro;
    // End of variables declaration//GEN-END:variables
}
